### ISSUE TITLE
[2주차] DRF Quickstart

### ISSUE THREAD

**Issue by joowankim** [BackendStudyOrg/DjangoTutorial#10]
1. REST API란?
2. Layered Architecture란?
3. [DRF Quickstart](https://www.django-rest-framework.org/tutorial/quickstart/) 따라해보기

**Comment by chldppwls12** [comment]
1. https://velog.io/@chldppwls12/REST-API%EB%9E%80
2. https://velog.io/@chldppwls12/%EA%B3%84%EC%B8%B5%ED%99%94-%EC%95%84%ED%82%A4%ED%85%8D%EC%B2%98Layered-Architecture

**Comment by ghost** [comment]
1. https://www.notion.so/REST-API-232433c9652b4563979e8efc8a78709e
2. https://www.notion.so/Layered-Architectur-b5ada1d517c64a7d981eeace6604b5a9
3. https://www.notion.so/Qucikstart-Djano-REST-framework-5a340e51537d4a39baf1417abb27ed16

**Comment by hjhjhj00** [comment]
1. https://www.notion.so/REST-API-786f04eb4d4842d3b22277f2192cbd01
2. https://www.notion.so/a35b783fce034832a2f8a20d2cf79a97
3. https://www.notion.so/Django-REST-Framework-quick-start-e27b80efd51a4d9499cbc7d6d515bac0
