### ISSUE TITLE
[1주차] Django Tutorial

### ISSUE THREAD

**Issue by joowankim** [BackendStudyOrg/DjangoTutorial#4]
1. [Django Getting Started](https://docs.djangoproject.com/en/3.2/intro/) 따라해보기
2. MVC 디자인 패턴

**Comment by ghost** [comment]
1. https://www.notion.so/Django-getting-start-bc3fae0cc8d947ef91b6e29cdff9c88f
2. https://www.notion.so/MVC-6e803ef38e2d44ea9a8b9fc06f71ac1d

**Comment by chldppwls12** [comment]
1. https://velog.io/@chldppwls12/Django-Tutorial-%EC%B2%AB%EB%B2%88%EC%A7%B8-%EC%9E%A5%EA%B3%A0-%EC%95%B1-%EC%9E%91%EC%84%B1%ED%95%98%EA%B8%B0-1
2. https://velog.io/@chldppwls12/Django-Tutorial-%EC%B2%AB%EB%B2%88%EC%A7%B8-%EC%9E%A5%EA%B3%A0-%EC%95%B1-%EC%9E%91%EC%84%B1%ED%95%98%EA%B8%B0-2
3. https://velog.io/@chldppwls12/Django-Tutorial-%EC%B2%AB%EB%B2%88%EC%A7%B8-%EC%9E%A5%EA%B3%A0-%EC%95%B1-%EC%9E%91%EC%84%B1%ED%95%98%EA%B8%B0-3
4. https://velog.io/@chldppwls12/Django-Tutorial-%EC%B2%AB%EB%B2%88%EC%A7%B8-%EC%9E%A5%EA%B3%A0-%EC%95%B1-%EC%9E%91%EC%84%B1%ED%95%98%EA%B8%B0-4
5. https://velog.io/@chldppwls12/Django-Tutorial-%EC%B2%AB%EB%B2%88%EC%A7%B8-%EC%9E%A5%EA%B3%A0-%EC%95%B1-%EC%9E%91%EC%84%B1%ED%95%98%EA%B8%B0-5
6. https://velog.io/@chldppwls12/Django-Tutorial-%EC%B2%AB%EB%B2%88%EC%A7%B8-%EC%9E%A5%EA%B3%A0-%EC%95%B1-%EC%9E%91%EC%84%B1%ED%95%98%EA%B8%B0-6
7. https://velog.io/@chldppwls12/django-MTV-%ED%8C%A8%ED%84%B4

**Comment by hjhjhj00** [comment]
https://www.notion.so/Django-5-ac94f47eb3cb44e4a9067a18ce94a151
